kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oauth-clusterrole
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - v1
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - appstudio.redhat.com
  resources:
  - spiaccesstokens
  verbs:
  - get
  - update
