kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: oauth-ingress
spec:
  rules:
  - host: $(OAUTH_HOST)
    http:
      paths:
      - backend:
          service:
            name: service
            port:
              name: oauth-port
        path: "/"
        pathType: Prefix
