kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oauth-role
rules:
- apiGroups:
  - v1
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - appstudio.redhat.com
  resources:
  - spiaccesstokenbindings
  verbs:
  - get
  - update
