kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/name: service-provider-integration-vault

configMapGenerator:
  - name: vault-poststart-script
    files:
      - poststart.sh
      - root.sh
      - spi_policy.hcl
