version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      # Check for updates on Saturdays
      day: "saturday"
  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      # Check for updates on Saturdays
      day: "saturday"
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      # Check for updates on Saturdays
      day: "saturday"