resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: manager-config
  files:
  - controller_manager_config.yaml

images:
- name: controller
  newName: quay.io/redhat-app-studio/service-provider-integration-operator
  newTag: latest
