kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- manager.yaml
- controller-manager-environment-config.yaml

commonLabels:
  app.kubernetes.io/name: service-provider-integration-operator
