kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/name: service-provider-integration-operator

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
