---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        env:
        - name: SPI_URL
          value: http://service-provider-integration-api
        image: controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: $(CONFIG_MOUNT_PATH)/config.yaml
          name: config
          subPath: config.yaml
        - mountPath: $(CONFIG_MOUNT_PATH)/shared-secret
          name: shared-secret
          subPath: shared-secret
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: oauth-config
      - name: shared-secret
        secret:
          secretName: shared-secret
