kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: spi-system

resources:
  - ../../bases/vault
  - ../../oauth/ingress
  - https://github.com/redhat-appstudio/application-api/config/crd?ref=e6c600a8c7324206833144dcdc710d7a982e63de

patches:
  - target:
      version: v1
      kind: ConfigMap
      name: shared-environment-config
      namespace: system
    patch: |-
      - op: add
        path: /data/VAULTINSECURETLS
        value: "true"

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: shared-configuration-file
    files:
      - config.yaml
