apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "appstudio.redhat.com/v1beta1",
          "kind": "SPIAccessToken",
          "metadata": {
            "name": "spiaccesstoken-sample"
          },
          "spec": {
            "foo": "bar"
          }
        },
        {
          "apiVersion": "appstudio.redhat.com/v1beta1",
          "kind": "SPIAccessTokenBinding",
          "metadata": {
            "name": "spiaccesstokenbinding-sample"
          },
          "spec": {
            "foo": "bar"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.12.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: service-provider-integration-operator.v0.3.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SPIAccessTokenBinding is the Schema for the spiaccesstokenbindings
        API
      displayName: SPIAccess Token Binding
      kind: SPIAccessTokenBinding
      name: spiaccesstokenbindings.appstudio.redhat.com
      version: v1beta1
    - description: SPIAccessToken is the Schema for the spiaccesstokens API
      displayName: SPIAccess Token
      kind: SPIAccessToken
      name: spiaccesstokens.appstudio.redhat.com
      version: v1beta1
  description: Service Provider operator
  displayName: Service Provider Service
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - get
          - list
          - watch
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - spiaccesstokenbindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - spiaccesstokenbindings/finalizers
          verbs:
          - update
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - spiaccesstokenbindings/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - spiaccesstokens
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - spiaccesstokens/finalizers
          verbs:
          - update
        - apiGroups:
          - appstudio.redhat.com
          resources:
          - spiaccesstokens/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: spi-controller-manager
      deployments:
      - name: spi-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: service-provider-integration-operator
              app.kubernetes.io/part-of: service-provider-integration-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                app.kubernetes.io/name: service-provider-integration-operator
                app.kubernetes.io/part-of: service-provider-integration-operator
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --leader-elect
                command:
                - /manager
                image: quay.io/redhat-appstudio/service-provider-integration-operator:next
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              securityContext:
                runAsNonRoot: true
              serviceAccountName: spi-controller-manager
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: webhook-server-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: spi-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - spi
  - service-provider
  - appstudio
  - redhat
  - kubernetes
  links:
  - name: Service Provider Integration Operator
    url: https://service-provider-integration-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.1.0
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    - v1beta1
    containerPort: 443
    deploymentName: spi-controller-manager
    failurePolicy: Fail
    generateName: spiaccesstoken-mwh.appstudio.redhat.com
    rules:
    - apiGroups:
      - appstudio.redhat.com
      apiVersions:
      - v1beta1
      operations:
      - CREATE
      - UPDATE
      resources:
      - spiaccesstokens
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /check-token
  - admissionReviewVersions:
    - v1
    - v1beta1
    containerPort: 443
    deploymentName: spi-controller-manager
    failurePolicy: Fail
    generateName: spiaccesstoken-vwh.appstudio.redhat.com
    rules:
    - apiGroups:
      - appstudio.redhat.com
      apiVersions:
      - v1beta1
      operations:
      - DELETE
      resources:
      - spiaccesstokens
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /check-token
  - admissionReviewVersions:
    - v1
    - v1beta1
    containerPort: 443
    deploymentName: spi-controller-manager
    failurePolicy: Fail
    generateName: spiaccesstokenbinding-vwh.appstudio.redhat.com
    rules:
    - apiGroups:
      - appstudio.redhat.com
      apiVersions:
      - v1beta1
      operations:
      - CREATE
      - UPDATE
      resources:
      - spiaccesstokenbindings
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-binding
