apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: service-provider-integration-operator
    app.kubernetes.io/part-of: service-provider-integration-operator
    control-plane: controller-manager
  name: spi-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: service-provider-integration-operator
    app.kubernetes.io/part-of: service-provider-integration-operator
    control-plane: controller-manager
status:
  loadBalancer: {}
