
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /check-token
  failurePolicy: Fail
  name: spiaccesstoken-wh.appstudio.redhat.com
  rules:
  - apiGroups:
    - appstudio.redhat.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spiaccesstokens
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /check-token
  failurePolicy: Fail
  name: spiaccesstoken-wh.appstudio.redhat.com
  rules:
  - apiGroups:
    - appstudio.redhat.com
    apiVersions:
    - v1beta1
    operations:
    - DELETE
    resources:
    - spiaccesstokens
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /check-binding
  failurePolicy: Fail
  name: spiaccesstokenbinding-wh.appstudio.redhat.com
  rules:
  - apiGroups:
    - appstudio.redhat.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spiaccesstokenbindings
  sideEffects: None
