apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-used
spec:
  template:
    spec:
      containers:
        - name: manager
          volumeMounts:
            - mountPath: /etc/spi/secret_id
              $patch: delete
            - mountPath: /etc/spi/role_id
              $patch: delete
            - mountPath: /etc/spi/aws/config
              name: aws-secretsmanager-credentials
              readOnly: true
              subPath: config
            - mountPath: /etc/spi/aws/credentials
              name: aws-secretsmanager-credentials
              readOnly: true
              subPath: credentials
      volumes:
        - name: vault-approle
          $patch: delete
        - name: aws-secretsmanager-credentials
          secret:
            secretName: aws-secretsmanager-credentials
            items:
              - key: config
                path: config
              - key: credentials
                path: credentials