---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spi-oauth-service
  namespace: spi-system
spec:
  template:
    spec:
      containers:
        - name: oauth
          volumeMounts:
          - mountPath: /etc/spi/tls.key
            name: tls-certificates
            readOnly: true
            subPath: tls.key
          - mountPath: /etc/spi/tls.crt
            name: tls-certificates
            readOnly: true
            subPath: tls.crt
      volumes:
      - name: tls-certificates
        secret:
          secretName: spi-oauth-service
          items:
            - key: tls.key
              path: tls.key
            - key: tls.crt
              path: tls.crt