# this is an example of a remote secret with a definition of the "shape" of the target secret
# but without any actual targets. This remote secret will just "sit and wait" until some targets
# are defined.
apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: test-remote-secret
  namespace: default
spec:
  secret:
    name: secret-from-remote
    type: Opaque

