# here, we provide the data to our remote secret so that we can start deploying.
apiVersion: v1
kind: Secret
metadata:
  name: test-remote-secret-secret
  labels:
    appstudio.redhat.com/upload-secret: remotesecret
  annotations:
    appstudio.redhat.com/remotesecret-name: test-remote-secret
type: Opaque
stringData:
  a: b
  c: d
