# in this example we modify the remote secret to have a single target.
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-target-ns-1
---  
apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: test-remote-secret
  namespace: default
spec:
  secret:
    name: secret-from-remote
    type: Opaque
  targets:
    - namespace: test-target-ns-1

