# here we change our spec so that there SAs associated with the secret in the targets.
apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: test-remote-secret
  namespace: default
spec:
  secret:
    name: secret-from-remote
    type: Opaque
    linkedTo:
    - serviceAccount:  
        managed:
          generateName: sa-in-remote-
  targets:
    - namespace: test-target-ns-1
    - namespace: test-target-ns-2
    - namespace: test-target-ns-3
