# this is almost the same remote secret as in step 6, but here we show
# that we don't leave "garbage" behind even when the secret is renamed.
apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: test-remote-secret
  namespace: default
spec:
  secret:
    name: secret-from-remote-renamed
    type: Opaque
  targets:
    - namespace: test-target-ns-1
    - namespace: test-target-ns-2
    - namespace: test-target-ns-3
