sharedSecret: ${SHARED_SECRET}
serviceProviders:
  - type: GitHub
    clientId: "123"
    clientSecret: "42"
  - type: Quay
    clientId: "456"
    clientSecret: "54"
baseUrl: https://${OAUTH_HOST}
vaultHost: https://${VAULT_HOST}
