kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: spi-system

resources:
  - ../default
  - route.yaml
  - ../prometheus

secretGenerator:
  - name: oauth-config
    files:
      - config.yaml
