# Adds namespace to all resources.
namespace: spi-system # WARN: keep this in sync with the namespace defined in the prepare base

images:
  - name: quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    newTag: next
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: quay.io/redhat-appstudio/service-provider-integration-oauth
    newTag: next

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/part-of: service-provider-integration-operator

resources:
  - ../default
  - route.yaml

secretGenerator:
  - name: oauth-config
    files:
      - config.yaml
