# permissions for end users to edit serviceproviderintergrationoperatorconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceproviderintergrationoperatorconfiguration-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - serviceproviderintergrationoperatorconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - serviceproviderintergrationoperatorconfigurations/status
  verbs:
  - get
