# permissions for end users to view serviceproviderintergrationoperatorconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceproviderintergrationoperatorconfiguration-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - serviceproviderintergrationoperatorconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - serviceproviderintergrationoperatorconfigurations/status
  verbs:
  - get
