# permissions for end users to edit spiaccesstokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spiaccesstoken-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - spiaccesstokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - spiaccesstokens/status
  verbs:
  - get
