# permissions for end users to view spiaccesstokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spiaccesstoken-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - spiaccesstokens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - spiaccesstokens/status
  verbs:
  - get
