# permissions for end users to view spiaccesschecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spiaccesscheck-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - spiaccesschecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - spiaccesschecks/status
  verbs:
  - get
