# permissions for end users to view spiaccesstokenbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spiaccesstokenbinding-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - spiaccesstokenbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - spiaccesstokenbindings/status
  verbs:
  - get
