# permissions for end users to edit spiaccesschecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spiaccesscheck-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - spiaccesschecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - spiaccesschecks/status
  verbs:
  - get
