kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: remotesecret

resources:
  - https://github.com/redhat-appstudio/remote-secret/config/overlays/minikube_vault?ref=30b49297823b148b33382948cf6c9d3b7d7fa96b

patches:
  - path: controller-manager-environment-config.yaml

