kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: remotesecret

resources:
  - https://github.com/redhat-appstudio/remote-secret/config/bases/vault?ref=9ebfe4979415b0d67de089f7d9e0b5458ed2be4c
  - ../../webhook/k8s

patches:
  - path: controller-manager-environment-config.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: controller-manager-environment-config
      namespace: remotesecret
    patch: |-
      - op: add
        path: /data/VAULTINSECURETLS
        value: "true"

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: shared-configuration-file
    files:
      - config.yaml
