kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: remotesecret

resources:
  - https://github.com/redhat-appstudio/remote-secret/config/overlays/minikube_vault?ref=ad62d5dcc56803caebabf3bea39e2bb0784f5167

patches:
  - path: controller-manager-environment-config.yaml

