global:
  enabled: true
  tlsDisable: true

injector:
  enabled: false

server:
  image:
    repository: docker.io/hashicorp/vault

  logLevel: "info"

  statefulSet:
    securityContext:
      container:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
              drop:
                - ALL
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 500Mi
      cpu: 500m

  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: null
    accessMode: ReadWriteOnce

  service:
    enabled: true

  ingress:
    enabled: true
    hosts:
    - host: ${VAULT_HOST}
      paths: []

  route:
    enabled: true
    host: null
    tls:
      termination: edge

  standalone:
    config: |
      ui = false

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "file" {
        path = "/vault/data"
      }

  ui:
    enabled: false

  serviceAccount:
    create: true

  postStart:
    - /bin/sh
    - /vault/userconfig/scripts/poststart.sh

  volumes:
    - name: poststart
      configMap:
        name: vault-poststart-script
        defaultMode: 0544
    - name: keys
      secret:
        secretName: spi-vault-keys
        optional: true
    - name: tmp
      emptyDir:
        medium: Memory
        sizeLimit: "64Mi"


  volumeMounts:
    - mountPath: /vault/userconfig/scripts
      name: poststart
    - mountPath: /vault/userconfig/keys
      name: keys
    - mountPath: /tmp
      name: tmp
