#!/bin/sh

helm repo add hashicorp https://helm.releases.hashicorp.com
helm repo update hashicorp

# Openshift template
echo "# This file is generated by './hack/vault-generate-template.sh'. Please do not edit this directly." > config/vault/openshift/deployment.yaml
helm template vault hashicorp/vault --set "global.openshift=true" --values hack/vault-helm-values.yaml --namespace system >> config/vault/openshift/deployment.yaml

# Kubernetes template
echo "# This file is generated by './hack/vault-generate-template.sh'. Please do not edit this directly." > config/vault/k8s/deployment.yaml
helm template vault hashicorp/vault --values hack/vault-helm-values.yaml --namespace system >> config/vault/k8s/deployment.yaml
