# This kustomization contains the configuration shared by the operator and the oauth service. The config.yaml map and the
# secret should be mounted into their respective deployments on the same path so that the below variable definition
# works in both deployments.
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- meta-config.yaml
- shared-secret.yaml

configurations:
- varconfig.yaml

configMapGenerator:
- name: oauth-config.yaml
  files:
  - config.yaml

vars:
- name: CONFIG_MOUNT_PATH
  objref:
    kind: ConfigMap
    apiVersion: v1
    name: oauth-metaconfig
  fieldref:
    fieldpath: data.config-mount-path
- name: OAUTH_HOST
  objref:
    kind: ConfigMap
    apiVersion: v1
    name: oauth-metaconfig
  fieldref:
    fieldpath: data.oauth-host
