# Adds namespace to all resources.
namespace: spi-system # WARN: keep this in sync with the namespace defined in the prepare base

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: spi- # WARN: keep this in sync with the namespace defined in the prepare base

images:
- name: quay.io/redhat-appstudio/service-provider-integration-operator
  newName: quay.io/redhat-appstudio/service-provider-integration-operator
  newTag: next
- name: quay.io/redhat-appstudio/service-provider-integration-oauth
  newName: quay.io/redhat-appstudio/service-provider-integration-oauth
  newTag: next

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/part-of: service-provider-integration-operator

resources:
# Common stuff with the prepare goal
- ../namespace
- ../crd
- ../rbac
- ../oauth
- ingress.yaml
- shared-config.yaml
# Additional stuff deployed by the default overlay
- ../manager

secretGenerator:
  - name: oauth-config
    files:
      - config.yaml

patches:
  - target:
      namespace: system
      kind: ConfigMap
      version: v1
      name: shared-config
    patch: |-
      - op: replace
        path: /data/VAULTAUTHMETHOD
        value: approle
  - target:
      namespace: system
      kind: Deployment
      version: v1
      group: apps
      name: controller-manager
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: vault-approle
          secret:
            secretName: vault-approle-spi-operator
            items:
              - key: role_id
                path: role_id
              - key: secret_id
                path: secret_id
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /etc/spi/role_id
          name: vault-approle
          readOnly: true
          subPath: role_id
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /etc/spi/secret_id
          name: vault-approle
          readOnly: true
          subPath: secret_id
  - target:
      namespace: system
      kind: Deployment
      version: v1
      group: apps
      name: oauth-service
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: vault-approle
          secret:
            secretName: vault-approle-spi-oauth
            items:
              - key: role_id
                path: role_id
              - key: secret_id
                path: secret_id
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /etc/spi/role_id
          name: vault-approle
          readOnly: true
          subPath: role_id
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /etc/spi/secret_id
          name: vault-approle
          readOnly: true
          subPath: secret_id
