apiVersion: appstudio.redhat.com/v1beta1
kind: ServiceProviderIntergrationOperatorConfiguration
metadata:
  name: serviceproviderintergrationoperatorconfiguration-sample
spec:
  # Add fields here
  foo: bar
