apiVersion: appstudio.redhat.com/v1beta1
kind: SPIAccessTokenBinding
metadata:
  name: binding-read-repository
spec:
  permissions:
    required:
      - type: r
        area: repository
  repoUrl: https://github.com/revapi/revapi
  secret:
    name: token-read-repository
    type: kubernetes.io/basic-auth
