apiVersion: appstudio.redhat.com/v1beta1
kind: SPIAccessTokenBinding
metadata:
  name: binding-sa
spec:
  permissions:
    required:
      - type: r
        area: repository
  repoUrl: https://github.com/revapi/revapi
  secret:
    name: token-sa
    type: kubernetes.io/basic-auth
    linkedTo:
    - serviceAccount:
        managed:
          generateName: token-sa-
