apiVersion: appstudio.redhat.com/v1beta1
kind: SPIAccessTokenBinding
metadata:
  name: test-binding-quay-without-protocol
  namespace: default
spec:
  permissions:
    required:
      - type: rw
        area: repository
  repoUrl: quay.io/repository/redhat_emp1/spi-test
  secret:
    type: kubernetes.io/basic-auth
