apiVersion: v1
kind: Secret
metadata:
  name: test-remote-secret-secret
  labels:
    spi.appstudio.redhat.com/upload-secret: remotesecret
  annotations:
    spi.appstudio.redhat.com/remotesecret-name: test-remote-secret
type: Opaque
stringData:
  a: b
  c: d

