apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: test-remote-secret
  namespace: default
  labels:
    appstudio.redhat.com/sp.host: github.com
  annotations:
    appstudio.redhat.com/sp.repository: redhat/somerepo,redhat/otherrepo # optional
spec:
  secret:
    type: kubernetes.io/basic-auth
    name: secret-from-remotesecret
  targets:
    - namespace: default
data:
  password: Z2VuYQ== # your GitHub personal access token