apiVersion: appstudio.redhat.com/v1beta1
kind: SPIAccessTokenBinding
metadata:
  name: test-access-token-binding-2
  namespace: default
spec:
  repoUrl: https://snyk.io/
  secret:
    type: kubernetes.io/basic-auth
