apiVersion: appstudio.redhat.com/v1beta1
kind: SPIAccessTokenBinding
metadata:
  name: test-access-token-binding-2
  namespace: default
spec:
  permissions:
    required:
      - type: rw
        area: repository
  repoUrl: https://github.com/revapi/revapi
  secret:
    type: kubernetes.io/basic-auth
