apiVersion: appstudio.redhat.com/v1beta1
kind: SPIAccessTokenBinding
metadata:
  name: test-access-token-binding
  namespace: default
spec:
  permissions:
    required:
      - type: r
        area: repository
      - type: w
        area: repository
  repoUrl: https://github.com/revapi/revapi
  secret:
    name: token-secret
    type: kubernetes.io/basic-auth
