apiVersion: appstudio.redhat.com/v1beta1
kind: SPIAccessTokenBinding
metadata:
  name: test-access-token-binding-3
  namespace: default
spec:
  permissions:
    required:
      - type: rw
        area: registry
  repoUrl: http://dummy-gitlab.com
  secret:
    type: kubernetes.io/basic-auth
