{
 "title": "SPI SLO",
 "description": "Profiling performance-related SPI metrics.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Token Data Update time",
   "type": "timeseries",
   "description": "The time it takes from the point in time the token data is uploaded into the Vault to it being picked up by the operator. This should be very similar to the reconcile time of the SPIAccessTokenDataUpdate object but will always be a little bit larger.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(redhat_appstudio_spi_spiaccesstokendataupdate_lifetime_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99% faster"
    }
   ]
  },
  {
   "title": "GitHub OAuth flow complete time",
   "type": "heatmap",
   "description": "The time that is user spent to complete GitHub OAuth flow.",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(redhat_appstudio_spi_oauth_flow_complete_time_seconds_bucket{type=\"GitHub\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Quay OAuth flow complete time",
   "type": "heatmap",
   "description": "The time that is user spent to complete Quay OAuth flow.",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "rate(redhat_appstudio_spi_oauth_flow_complete_time_seconds_bucket{type=\"Quay\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GitLab OAuth flow complete time",
   "type": "heatmap",
   "description": "The time that is user spent to complete GitLab OAuth flow.",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "rate(redhat_appstudio_spi_oauth_flow_complete_time_seconds_bucket{type=\"GitLab\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Quay Metadata Fetch",
   "type": "timeseries",
   "description": "The overall time to fetch the metadata of a single repository for a single token in Quay. This is a compound of the number of requests to Quay + the processing and storage time.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by() (rate(redhat_appstudio_spi_quay_single_repo_metadata_fetch_seconds_count[$__rate_interval]))",
     "legendFormat": "total fetches"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(redhat_appstudio_spi_quay_single_repo_metadata_fetch_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99% responses faster"
    }
   ]
  },
  {
   "title": "Github Metadata Fetch",
   "type": "timeseries",
   "description": "The overall time to fetch the metadata of all repositories accessible by a single token in Github. This is a compound of the number of requests to Github + the processing and storage time.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(redhat_appstudio_spi_github_token_metadata_fetch_seconds_count[$__rate_interval]))",
     "legendFormat": "total fetches"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(redhat_appstudio_spi_github_token_metadata_fetch_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99% responses faster"
    }
   ]
  },
  {
   "title": "GitLab Metadata Fetch",
   "type": "timeseries",
   "description": "The overall time to fetch the metadata of a single token in GitLab.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(redhat_appstudio_spi_gitlab_token_metadata_fetch_seconds_count[$__rate_interval]))",
     "legendFormat": "total fetches"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(redhat_appstudio_spi_gitlab_token_metadata_fetch_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99% responses faster"
    }
   ]
  },
  {
   "title": "GitHub 5xx responses percentage",
   "type": "timeseries",
   "description": "The percentage of 5xx responses returned from GitHub in general responses count.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(redhat_appstudio_spi_service_provider_response_time_seconds_count{sp=\"GitHub\",status=~\"5..\"}[24h]) OR on() vector(0)) / sum(increase(redhat_appstudio_spi_service_provider_response_time_seconds_count{sp=\"GitHub\"}[24h]))",
     "legendFormat": "5xx percentage"
    }
   ]
  },
  {
   "title": "GitLab 5xx responses percentage",
   "type": "timeseries",
   "description": "The percentage of 5xx responses returned from GitLab in general responses count.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(redhat_appstudio_spi_service_provider_response_time_seconds_count{sp=\"GitLab\",status=~\"5..\"}[24h]) OR on() vector(0)) / sum(increase(redhat_appstudio_spi_service_provider_response_time_seconds_count{sp=\"GitLab\"}[24h]))",
     "legendFormat": "5xx percentage"
    }
   ]
  },
  {
   "title": "Quay 5xx responses percentage",
   "type": "timeseries",
   "description": "The percentage of 5xx responses returned from Quay in general responses count.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(redhat_appstudio_spi_service_provider_response_time_seconds_count{sp=\"Quay\",status=~\"5..\"}[24h]) OR on() vector(0)) / sum(increase(redhat_appstudio_spi_service_provider_response_time_seconds_count{sp=\"Quay\"}[24h]))",
     "legendFormat": "5xx percentage"
    }
   ]
  }
 ]
}