{
 "title": "SPI Outbound traffic",
 "description": "The measurements of the outbound requests made by the operator.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Github Metadata Fetch",
   "type": "timeseries",
   "description": "The overall time to fetch the metadata of all repositories accessible by a single token in Github. This is a compound of the number of requests to Github + the processing and storage time.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(redhat_appstudio_spi_github_token_metadata_fetch_seconds_count[$__rate_interval]))",
     "legendFormat": "total fetches"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(redhat_appstudio_spi_github_token_metadata_fetch_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99% responses faster"
    }
   ]
  },
  {
   "title": "Github Requests per day",
   "type": "gauge",
   "description": "The number of individual requests made to the Github API in the last 24 hours.",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(redhat_appstudio_spi_service_provider_request_count_total{sp=\"GitHub\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GitLab Metadata Fetch",
   "type": "timeseries",
   "description": "The overall time to fetch the metadata of a single token in GitLab.",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(redhat_appstudio_spi_gitlab_token_metadata_fetch_seconds_count[$__rate_interval]))",
     "legendFormat": "total fetches"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(redhat_appstudio_spi_gitlab_token_metadata_fetch_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99% responses faster"
    }
   ]
  },
  {
   "title": "GitLab Requests per day",
   "type": "gauge",
   "description": "The number of individual requests made to the GitLab API in the last 24 hours.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(redhat_appstudio_spi_service_provider_request_count_total{sp=\"GitLab\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Github Metadata Fetch Mean",
   "type": "gauge",
   "description": "The mean of the overall time to fetch the metadata of all repositories accessible by a single token in Github.",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redhat_appstudio_spi_github_token_metadata_fetch_seconds_sum{failure=\"false\"}) / sum(redhat_appstudio_spi_github_token_metadata_fetch_seconds_count{failure=\"false\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GitLab Metadata Fetch Mean",
   "type": "gauge",
   "description": "The mean of the overall time to fetch the metadata of a single token in GitLab.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redhat_appstudio_spi_gitlab_token_metadata_fetch_seconds_sum{failure=\"false\"}) / sum(redhat_appstudio_spi_gitlab_token_metadata_fetch_seconds_count{failure=\"false\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quay Metadata Fetch",
   "type": "timeseries",
   "description": "The overall time to fetch the metadata of a single repository for a single token in Quay. This is a compound of the number of requests to Quay + the processing and storage time.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by() (rate(redhat_appstudio_spi_quay_single_repo_metadata_fetch_seconds_count[$__rate_interval]))",
     "legendFormat": "total fetches"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(redhat_appstudio_spi_quay_single_repo_metadata_fetch_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99% responses faster"
    }
   ]
  },
  {
   "title": "Quay Requests per day",
   "type": "gauge",
   "description": "The number of individual requests made to the Quay API (both REST and docker endpoints) in the last 24 hours.",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(redhat_appstudio_spi_service_provider_request_count_total{sp=\"Quay\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GitHub Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(redhat_appstudio_spi_github_rate_limit_errors[$__rate_interval])",
     "legendFormat": "rate limit errors"
    },
    {
     "expr": "sum by(unexpected_status) (rate(redhat_appstudio_spi_github_public_repo_unexpected_response_status[$__rate_interval]))",
     "legendFormat": "status {{unexpected_status}}"
    }
   ]
  },
  {
   "title": "Quay Metadata Fetch Mean",
   "type": "gauge",
   "description": "The mean of the overall time to fetch the metadata of a single repository for a single token in Quay.",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redhat_appstudio_spi_quay_single_repo_metadata_fetch_seconds_sum{failure=\"false\"}) / sum(redhat_appstudio_spi_quay_single_repo_metadata_fetch_seconds_count{failure=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Provider Requests",
   "type": "timeseries",
   "description": "The individual requests made to the service providers.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(sp, status, hostname, operation) (rate(redhat_appstudio_spi_service_provider_response_time_seconds_count[$__rate_interval]))",
     "legendFormat": "{{sp}} {{hostname}} {{status}} {{operation}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, sp, status, hostname, operation) (rate(redhat_appstudio_spi_service_provider_response_time_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vault",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(method, status) (rate(redhat_appstudio_spi_vault_request_count_total[$__rate_interval]))",
     "legendFormat": "{{method}} {{status}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(redhat_appstudio_spi_vault_response_time_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99% responses below"
    }
   ]
  },
  {
   "title": "GitHub OAuth flow complete time",
   "type": "heatmap",
   "description": "The time that is user spent to complete GitHub OAuth flow.",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(redhat_appstudio_spi_oauth_flow_complete_time_seconds_bucket{type=\"GitHub\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Quay OAuth flow complete time",
   "type": "heatmap",
   "description": "The time that is user spent to complete Quay OAuth flow.",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "rate(redhat_appstudio_spi_oauth_flow_complete_time_seconds_bucket{type=\"Quay\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GitLab OAuth flow complete time",
   "type": "heatmap",
   "description": "The time that is user spent to complete GitLab OAuth flow.",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "rate(redhat_appstudio_spi_oauth_flow_complete_time_seconds_bucket{type=\"GitLab\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}