kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: spi-system

resources:
  - ../../bases/openshift-vault

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: shared-configuration-file
    files:
      - config.yaml
