---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcp-manager-role
rules:
- apiGroups:
  - apis.kcp.dev
  resources:
  - apiexports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apis.kcp.dev
  resources:
  - apiexports/content
  verbs:
  - '*'
