kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: spi-system
generatorOptions:
  disableNameSuffixHash: true
resources:
  - apiexport_spi.yaml
  - apiresourceschema_spi.yaml
  - apiexport_spi_clusterrole.yaml
  - apiexport_spi_clusterrolebinding.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - ../default

secretGenerator:
  - name: shared-configuration-file
    files:
      - config.yaml

# CRDs on KCP collides with APIResourceSchemas/APIExports so we don't want to deploy them
patchesStrategicMerge:
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: spiaccesschecks.appstudio.redhat.com
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: spiaccesstokenbindings.appstudio.redhat.com
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: spiaccesstokendataupdates.appstudio.redhat.com
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: spiaccesstokens.appstudio.redhat.com
    $patch: delete
