kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: spi-system

resources:
  - apiexport_spi.yaml
  - apiresourceschema_spi.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - ../default

secretGenerator:
  - name: oauth-config
    files:
      - config.yaml
