---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spi-oauth-service
  namespace: spi-system
spec:
  template:
    spec:
      containers:
      - name: oauth
        volumeMounts:
          - mountPath: /etc/spi/secret_id
            name: vault-approle
            readOnly: true
            subPath: secret_id
          - mountPath: /etc/spi/role_id
            name: vault-approle
            readOnly: true
            subPath: role_id
      volumes:
        - name: vault-approle
          secret:
            secretName: vault-approle-spi-oauth
            items:
              - key: role_id
                path: role_id
              - key: secret_id
                path: secret_id
