kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: spi-system

resources:
  - ../../default
  - route.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: shared-configuration-file
    files:
      - config.yaml

patches:
  - target:
      version: v1
      kind: ConfigMap
      name: shared-environment-config
      namespace: system
    patch: |-
      - op: add
        path: /data/TOKENSTORAGE
        value: "vault"
