kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../default

patches:
  - path: operator-aws-patch.yaml
  - path: oauth-aws-patch.yaml
  - path: shared-config-patch.yaml
