---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: spi-operator-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]" 
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: git-url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: output-image
      value: 'quay.io/redhat-appstudio/service-provider-integration-operator:{{ revision }}'
    - name: path-context
      value: .
    - name: dockerfile
      value: Dockerfile
    - name: infra-deployment-update-script
      value: |
        sed -i -e 's|\(https://github.com/redhat-appstudio/service-provider-integration-operator/config/kcp_openshift?ref=\)\(.*\)|\1{{ revision }}|' components/spi/base/kustomization.yaml;
        awk  -i inplace -v n=1 '/newTag:/ { if (++count == n) sub(/newTag:.*/, "newTag: {{ revision }}")} 1' components/spi/base/kustomization.yaml
        sed -i -e 's|\(https://raw.githubusercontent.com/redhat-appstudio/service-provider-integration-operator/\)\(.*\)|\1{{ revision }}/hack/vault-init.sh|' hack/preview.sh;
        sed -i -e 's|\(https://github.com/redhat-appstudio/service-provider-integration-operator/config/vault/openshift?ref=\)\(.*\)|\1{{ revision }}|' components/spi/vault/kustomization.yaml
  pipelineRef:
    name: docker-build
    bundle: quay.io/redhat-appstudio/hacbs-core-service-templates-bundle:latest
  workspaces: 
   - name: workspace 
     persistentVolumeClaim: 
        claimName: app-studio-default-workspace 
     subPath: spi-operator-push-{{ revision }}
