apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: spi-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
#spec
spec:
  params:
    - name: git-repo-url
      value: "{{repo_url}}"
    - name: git-revision
      value: "{{revision}}"
    - name: output-image
      value: 'quay.io/ejegrova/service-provider-integration-operator:{{revision}}'
    - name: path-context
      value: .
    - name: dockerfile
      value: Dockerfile
  pipelineRef:
    name: docker-build
    bundle: quay.io/redhat-appstudio/build-templates-bundle:93dac682ee16a08634d593b836758e1d4fa8d967
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: app-studio-default-workspace
      subPath: service-provider-integration-operator-{{git-revision}} 
