apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: spi-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: git-url
      value: 'https://github.com/redhat-appstudio/service-provider-integration-operator'
    - name: revision
      value: $(git-revision)
    - name: output-image
      value: 'quay.io/redhat-appstudio/service-provider-integration-operator:$(git-revision)'
    - name: path-context
      value: appstudio-utils
  pipelineRef:
    name: docker-build
    bundle: quay.io/redhat-appstudio/build-templates-bundle:b2cb5d5b21dc59d172379e639b336533bd8a8bf6
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: app-studio-default-workspace
      subPath: service-provider-integration-operator-{{git-revision}} 
