kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: grafana-operator-system


generatorOptions:
  disableNameSuffixHash: true


configMapGenerator:
  - name: grafana-dashboard-spi-health
    files:
      - grafana-dashboards/spi-health.json
  - name: grafana-dashboard-spi-outbound-traffic
    files:
      - grafana-dashboards/spi-outbound-traffic.json
  - name: grafana-dashboard-spi-slo
    files:
      - grafana-dashboards/spi-slo.json
