{
 "title": "SPI Health",
 "description": "The CPU time, memory consumption and reconcile times of the SPI operator and OAuth service.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Operator CPU time",
   "type": "timeseries",
   "description": "The show the CPU time as a portion of time the operator process occupied the CPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"spi-controller-manager-metrics-service\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OAuth Service CPU time",
   "type": "timeseries",
   "description": "The show the CPU time as a portion of time the OAuth service process occupied the CPU",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"spi-oauth-metrics-service\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Operator memory",
   "type": "timeseries",
   "description": "The memory consumed by the operator. This is the sum of the resident and the virtual memory.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"spi-controller-manager-metrics-service\"} + process_virtual_memory_bytes",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OAuth Service memory",
   "type": "timeseries",
   "description": "The memory consumed by the OAuth service. This is the sum of the resident and the virtual memory.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"spi-oauth-metrics-service\"} + process_virtual_memory_bytes",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Reconcile times",
   "type": "timeseries",
   "description": "The time it takes the operator to reconcile an object of the given type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, controller) (rate(controller_runtime_reconcile_time_seconds_bucket{namespace=\"spi-system\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token Data Update time",
   "type": "timeseries",
   "description": "The time it takes from the point in time the token data is uploaded into the Vault to it being picked up by the operator. This should be very similar to the reconcile time of the SPIAccessTokenDataUpdate object but will always be a little bit larger.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(redhat_appstudio_spi_spiaccesstokendataupdate_lifetime_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99% faster"
    }
   ]
  },
  {
   "title": "OAuth Service Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(method, code) (rate(redhat_appstudio_spi_oauth_service_requests_total[$__rate_interval]))",
     "legendFormat": "{{method}} {{code}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(redhat_appstudio_spi_oauth_service_response_time_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99% responses below"
    }
   ]
  }
 ]
}