apiVersion: appstudio.redhat.com/v1alpha1
kind: Environment
metadata:
  name: development
  namespace: default
  labels:
    toolchain.dev.openshift.com/owner: mshaposh
    toolchain.dev.openshift.com/provider: codeready-toolchain
spec:
  deploymentStrategy: AppStudioAutomated
  displayName: Development
  type: Non-POC