apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: test-remote-secret
  namespace: default
  labels:
    appstudio.application: so-sample
    appstudio.environment: development
spec:
  secret:
    name: secret-from-remote
    type: Opaque