kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: grafana-operator-system


generatorOptions:
  disableNameSuffixHash: true


configMapGenerator:
  - name: grafana-dashboard-prometheus-2-0-overview
    files:
      - grafana-dashboards/prometheus-2-0-overview_rev1.json
  - name: grafana-dashboard-controller-runtime
    files:
      - grafana-dashboards/controller-runtime-controllers-detail_rev1.json
  - name: grafana-dashboard-go-processes
    files:
      - grafana-dashboards/go-processes_rev1.json
  - name: grafana-dashboard-spi-health
    files:
      - grafana-dashboards/spi-health.json
  - name: grafana-dashboard-spi-outbound-traffic
    files:
      - grafana-dashboards/spi-outbound-traffic.json
  - name: grafana-dashboard-spi-slo
    files:
      - grafana-dashboards/spi-slo.json